#!/usr/bin/env zsh
# shellcheck disable=SC2155
# ==================================================================
# .ZSH* FILE PROCESSING ORDER:
# .zshenv -> .zprofile -> .zshrc -> .zlogin -> .zlogout
# ==================================================================

export SESSION_START="$(date -Iseconds)"

# Don't re-run this
if [ -n "$ENV_SET" ]; then exit 0; fi

# ------------------------------------------------------------------
# OWNERSHIP VARIABLES
# ------------------------------------------------------------------

export USERNAME="$(whoami)"

# ------------------------------------------------------------------
# XDG PATH VARIABLES
# ------------------------------------------------------------------
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.cache
# ------------------------------------------------------------------
export XDG_DESKTOP_DIR="$HOME"/Desktop
export XDG_DOWNLOAD_DIR="$XDG_DOWNLOAD_DIR"
export XDG_DOCUMENTS_DIR="$HOME"/Documents
export XDG_MUSIC_DIR="$HOME"/Music
export XDG_PICTURES_DIR="$HOME"/Pictures
export XDG_VIDEOS_DIR="$HOME"/Videos
export XDG_TEMPLATES_DIR="$HOME"/Templates
export XDG_PUBLICSHARE_DIR="$HOME"/Public
# ------------------------------------------------------------------
# XDG_DATA_DIRS FUNCTIONS
# ------------------------------------------------------------------
xdg::data::add()
{
	local pos="${2:-tail}"

	if ! grep -q "$1" <<< "$XDG_DATA_DIRS"; then
		case "$pos" in
			head) XDG_DATA_DIRS="$1${XDG_DATA_DIRS:+":$XDG_DATA_DIRS"}";;
			tail) XDG_DATA_DIRS="${XDG_DATA_DIRS:+"$XDG_DATA_DIRS:"}$1";;
		esac
	fi
}
xdg::data::head() { xdg::data::add "$1" head; }
xdg::data::tail() { xdg::data::add "$1" tail; }
# ------------------------------------------------------------------
# XDG_DATA_DIRS
# ------------------------------------------------------------------
XDG_DATA_DIRS=/usr/local/share
xdg::data::add "/usr/share"
xdg::data::add "$XDG_DATA_HOME"
export XDG_DATA_DIRS
# ------------------------------------------------------------------
export XDG_DIRS=("XDG_DATA_HOME" "XDG_DATA_DIRS" "XDG_CONFIG_HOME" "XDG_CONFIG_DIRS" "XDG_STATE_HOME" "XDG_CACHE_HOME" "XDG_DESKTOP_DIR" "XDG_DOWNLOAD_DIR" "XDG_DOCUMENTS_DIR" "XDG_MUSIC_DIR" "XDG_PICTURES_DIR" "XDG_VIDEOS_DIR" "XDG_TEMPLATES_DIR" "XDG_PUBLICSHARE_DIR")
# ------------------------------------------------------------------
# MANPATH FUNCTIONS
# ------------------------------------------------------------------
man::path::add()
{
	local pos="${2:-tail}"

	if ! grep -q "$1" <<< "$MANPATH"; then
		case "$pos" in
			head) MANPATH="$1${MANPATH:+":$MANPATH"}";;
			tail) MANPATH="${MANPATH:+"$MANPATH:"}$1";;
		esac
	fi
}
man::path::head() { man::path::add "$1" head; }
man::path::tail() { man::path::add "$1" tail; }
# ------------------------------------------------------------------
# MANPATH
# ------------------------------------------------------------------
man::path::add "/usr/share/man"
man::path::add "/usr/local/share/man"
man::path::add "$HOME/.local/man"
man::path::add "$HOME/.local/share/man"
export MANPATH
# ------------------------------------------------------------------
# PATH FUNCTIONS
# ------------------------------------------------------------------
path::add()
{
	local pos="${2:-tail}"

	if ! grep -q "$1" <<< "$PATH"; then
		case "$pos" in
			head) PATH="$1${PATH:+":$PATH"}";;
			tail) PATH="${PATH:+"$PATH:"}$1";;
		esac
	fi
}
path::head() { path::add "$1" head; }
path::tail() { path::add "$1" tail; }
# ------------------------------------------------------------------
# PATH
# ------------------------------------------------------------------
path::tail "/usr/local/sbin"
path::tail "/usr/local/bin"
path::tail "/usr/sbin"
path::tail "/usr/bin"
path::tail "/sbin"
path::tail "/bin"
path::head "$HOME/.local/sbin"
path::head "$HOME/.local/bin"
export PATH
# ------------------------------------------------------------------
# ZSH VARIABLES
# ------------------------------------------------------------------
# launchctl setenv ZDOTDIR="$HOME"
# launchctl setenv ZSHDIR="$HOME"/.zsh
export ZDOTDIR="$HOME"
export ZSHDIR="$HOME"/.zsh
export ZSH="$HOME"/.oh-my-zsh
export ZSH_CUSTOM="$ZSH/custom"
export ZSH_CUSTOM_PLUGINS="$ZSH_CUSTOM/plugins"
export ZSHSHARE="${XDG_DATA_DIRS%%:*}"
# ------------------------------------------------------------------
# ZSH EXCLUDED VARIABLES
# ------------------------------------------------------------------
export ZSHEXCLUDE_ALIASES=()
export ZSHEXCLUDE_BINDINGS=()
export ZSHEXCLUDE_COMPLETION=()
export ZSHEXCLUDE_FUNCTIONS=()
# ------------------------------------------------------------------
# MISC PATHS
# ------------------------------------------------------------------
export LOGDIR="$ZSHSHARE/log"
export SSHDIR="$HOME"/.ssh
export GNUPGHOME="$HOME"/.gnupg
export INFOPATH="/usr/local/share/info:$INFOPATH"
# ------------------------------------------------------------------
# GIT ENV VARIABLES
# ------------------------------------------------------------------
export GIT_USER="$(git config --global --get user.name)"
export GIT_EMAIL="$(git config --global --get user.email)"
export GIT_FILEMODE="$(git config --global --get core.filemode)"
export GIT_EOL="$(git config --global --get core.eol)"
export GIT_AUTOCRLF="$(git config --global --get core.autocrlf)"
# ------------------------------------------------------------------
# TELEMETRY OPT-OUT
# ------------------------------------------------------------------
export DO_NOT_TRACK=1					# https://consoledonottrack.com/
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=1
export HINT_TELEMETRY="off"
export GATSBY_TELEMETRY_OPT_OUT=1
export NEXT_TELEMETRY_DEBUG=1
export NUXT_TELEMETRY_DISABLED=1
export ET_NO_TELEMETRY=1
export INFLUXD_REPORTING_DISABLED=true
export NG_CLI_ANALYTICS=false
export CHOOSENIM_NO_ANALYTICS=1
export POWERSHELL_TELEMETRY_OPTOUT=1
# ------------------------------------------------------------------
# MISC ENV VARIABLES
# ------------------------------------------------------------------
export EDITOR="pico"
export LC_ALL="en_AU.UTF-8"
export SYMBOL_ERROR="✘"
export SYMBOL_SUCCESS="✔"
export SYMBOL_INFO="ℹ️"
export SYMBOL_WARNING="⚠️"
export LC_TIME=C					# 24-hour date
export LANG=en_AU.UTF-8
export TZ="Australia/Brisbane"
export AUTH_AGENT="ssh"

umask 022

export ENV_SET=1
