#!/usr/bin/env zsh
# shellcheck disable=SC1090,SC2034,SC2154
# ==================================================================
# .ZSH* FILE PROCESSING ORDER:
# .zshenv -> .zprofile -> .zshrc -> .zlogin -> .zlogout
# ==================================================================

if [[ -d "$ZSH_CUSTOM/plugins/themes/powerlevel10k" ]]; then
	# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
	# Initialization code that may require console input (password prompts, [y/n]
	# confirmations, etc.) must go above this block; everything else may go below.
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi
fi

source "$ZSHSHARE/zshrc"

# ==================================================================
# USER CONFIGURATION / OVERRIDES
# ==================================================================

# ------------------------------------------------------------------
# USER VARIABLES
# ------------------------------------------------------------------
export COLUMS ROWS

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nano'
else
	export EDITOR='pico'
fi

if [ -z "$PROFILE_SET" ]; then
	source "$USERDIR/.profile"
	export PROFILE_SET='zshrc'
fi

# ------------------------------------------------------------------
# THEME
# ------------------------------------------------------------------
# If set to "random", then a random theme will be loaded each time oh-my-zsh is loaded.
# If you need to know which theme was randomly loaded, run: `echo $RANDOM_THEME`
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
if [[ ! -d "$ZSH_CUSTOM/plugins/themes/powerlevel10k" ]]; then ZSH_THEME="bira"; fi

if [[ -d "$ZSH_CUSTOM/plugins/themes/powerlevel10k" ]]; then
	ZSH_THEME="powerlevel10k/powerlevel10k"

	# ------------------------------------------------------------------
	# POWERLEVEL10K THEME
	# ------------------------------------------------------------------
	typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

	if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-$USERNAME.zsh" ]]; then
		source "$XDG_CACHE_HOME/p10k-instant-prompt-$USERNAME.zsh"
	fi
fi
