#!/usr/bin/env zsh

# ==================================================================
# help-swarm
# ==================================================================
# Swarm Cookbook Installer
#
# File:         help-swarm
# Author:       Ragdata
# Date:         15/04/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
# DEPENDENCIES
# ==================================================================

# ==================================================================
# MAIN
# ==================================================================
echo
echo "${GOLD}======================================================${RESET}"
echo "${GOLD}/usr/local/bin/${RESET}${WHITE}swarm${RESET} ${GOLD}COMMAND USAGE${RESET}"
echo "${GOLD}======================================================${RESET}"
echo
echo "${GOLD}Logs:${RESET}"
echo     "    swarm -l|--logs follow [OPTIONS] CONTAINER        - Automatically follow logFiles by scrolling text"
echo 	 "    swarm -l|--logs tail FILENAME                     - Output the last 50 lines of the specified file"
echo     "    swarm -l|--logs CONTAINER                         - View logs for the specified container"
