#!/usr/bin/env zsh
# shellcheck disable=SC1090
# ==================================================================
# .zsh_aliases
# ==================================================================
# This file exists so that you may add any alias files you require
# ==================================================================
# LOAD DOTFILES
# ==================================================================
source="$ZSHDIR/aliases"
while IFS= read -r file
do
	fileName="${file##*/}"
	# check that file is not excluded, and is not a backup
	if [[ "${ZSHEXCLUDE_ALIASES[(ie)${fileName}]}" -lt "${#ZSHEXCLUDE_ALIASES}" ]] && [[ "${fileName:((${#fileName}-1)):1}" != "~" ]]; then source "$source/$fileName"; fi
done < <(find "$source" -type f)
# ==================================================================
# ALIAS FUNCTIONS
# ==================================================================
