#!/usr/bin/env zsh
# shellcheck disable=SC1090
# ==================================================================
# .zsh_completion
# ==================================================================
zstyle 'completion:*:*:git:*' script "$ZSHDIR"/completion/git-completion.bash
zstyle 'completion:*:*:git:*' script "$ZSHDIR"/completion/_git

fpath=("$ZSHDIR"/completion "$fpath")
fpath=("$fpath" "/usr/share/zsh/functions/Completion")

autoload -U compinit; compinit
